services:
  employeehub.server:
    image: ${DOCKER_REGISTRY-}employeehubserver
    build:
      context: .
      dockerfile: EmployeeHub.Server/Dockerfile
    depends_on:
      - employee.db
    environment:
      - ConnectionString=Server=employee.db;Database=EmployeeDb;User Id=sa;Password=;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/employyes.pfx
    volumes:
      - ~/.aspnet/https:/https:ro 

  employee.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=
volumes:
  aspnet-certs:
    driver: local